version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./app"]
